name: expense-tracker
networks:
  default:
    name: expense
volumes:
  mysql-data:
    external: true #we need to create this volume before running the docker-compose file, using the command: docker volume create mysql-data
services:
  mysql:
    #image: mysql:v1.0
    image: tgsmanimohan/mysql:v1.0
    container_name: mysql
    volumes: 
      - source: mysql-data
        target: /var/lib/mysql
        type: volume
  backend:
    image: backend:v1.0
    container_name: backend
    command: sh -c "sleep 30 && node /app/index.js"
    depends_on: 
    - mysql
    ports:
    - "8080:8080"
  frontend:
    image: frontend:v1.0
    container_name: frontend
    depends_on: 
    - backend
    ports:
    - "80:80"